#!/bin/bash

file=$1
file_new=${file%.cnf}.dimacs
javaSource=
solverSource=
modelSource=

for i in "$@"; do
  case $i in
    --maxrss=*)
      MAXRSS="${i#*=}"
      shift # past argument=value
      ;;
    --maxtmp=*)
      MAXTMP="${i#*=}"
      shift # past argument=value
      ;;
    --timeout=*)
      TIMEOUT="${i#*=}"
      shift # past argument=value
      ;;
    -*|--*)
      echo "c o Ignore option $i"
      ;;
    *)
      ;;
  esac
done

mv -- "$file" "$file_new"

./$javaSource -Djava.io.tmpdir=$TMPDIR -jar $solverSource -cnfFile $file_new -modelFile $modelSource -maxrss $MAXRSS -maxtmp $MAXTMP -timeout $TIMEOUT -tmpdir $TMPDIR